.TH ZSTR_LENGTH_POSITIVE 3 libzahl
.SH NAME
zstr_length_positive - Predict the length of a string
.SH SYNOPSIS
.nf
#include <zahl.h>

size_t zstr_length_positive(z_t \fIa\fP, unsigned long long int\fIradix\fP);
.fi
.SH DESCRIPTION
.B zstr_length_positive
calculates the number of digits required to
to represent
.I a
in the selected
.IR radix .
.P
.I a
must be a positive integer. If it is zero or negative,
undefined behaviour is invoked.
.SH RETURN VALUE
The number of digits requires to represent
.I a
i the selected
.I radix
is returned.
.SH SEE ALSO
.BR zstr (3)
